modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Chainmail-Studios/Astromine/issues"
[[mods]]
    modId="astromine"
    version="${version}"
    displayName="Astromine"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/astromine-main"
    logoFile="icon.png"
    credits=""
    authors="vini2003, Shnupbups, Zundrel, shedaniel, MoonlitLamps, SuperCoder79, Draylar, HalfOf2, Martmists, AK9"
    description='''A space-themed technological modification with exploration, weapons and progression in mind.'''
[[dependencies.astromine]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.astromine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
