modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Mixinors/Astromine/issues"
[[mods]]
    modId="astrominecore"
    version="${version}"
    displayName="Astromine: Core"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/astromine-core"
    logoFile="icon.png"
    credits=""
    authors="vini2003, Shnupbups, Zundrel, shedaniel, MoonlitLamps, SuperCoder79, Draylar, HalfOf2, Martmists, AK9"
    description='''The core dependencies and utilities required for all other Astromine modules.'''
[[dependencies.astrominecore]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominecore]]
    modId="astromine"
    mandatory=false
    ordering="AFTER"
    side="BOTH"
