modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Mixinors/Astromine/issues"
[[mods]]
    modId="astrominetechnologies"
    version="${version}"
    displayName="Astromine: Technologies"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/astromine-technologies"
    logoFile="icon.png"
    credits=""
    authors="vini2003, Shnupbups, Zundrel, shedaniel, MoonlitLamps, SuperCoder79, Draylar, HalfOf2, Martmists, AK9"
    description='''The machinery module of Astromine.'''
[[dependencies.astrominetechnologies]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominetechnologies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominetechnologies]]
    modId="astromine"
    mandatory=false
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominetechnologies]]
    modId="astrominecore"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.astrominetechnologies]]
    modId="astrominefoundations"
    mandatory=true
    ordering="NONE"
    side="BOTH"
